name: Auto Build

on: 
    push:
        branches:
        - master
    # pull_request:
    #     branches:
    #     - master

jobs:
    deploy:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: Build
          run: |
                echo "Build" && \
                cd /app/xianju-python-service-compose/xianju-admin-frontend && \
                npm run build